{
 "title": "App dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{instance=\"host.docker.internal:7242\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Product Sales by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "round(sum by (product_type) (increase(pizzeria_product_sold_total[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max(rate(process_cpu_time_seconds_total[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg cooking time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(pizzeria_product_cooking_time_milliseconds_sum[1m]))\n  /\navg(rate(pizzeria_product_cooking_time_milliseconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}